[core]
Path = recipes/core

[extra]
Path = recipes/extra

[desktop]
Path = recipes/desktop

[xfce]
Path = recipes/xfce

[pkgs-core]
Path = pkgs/core

[pkgs-extra]
Path = pkgs/extra

[pkgs-desktop]
Path = pkgs/desktop